### PR TITLE
Bugfix: NaN values after df processing

### PR DESCRIPTION
**Pull request by chauhankaranraj**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## Description

While working on the visualization notebook, we noticed that the values for the `pct_fixed` KPI were NaN for all rows in all files. On further inspecting the `pct_fixed` notebook, we saw that in the last step before saving to ceph, the df conversion was causing the values to be all NaN's. This PR should fix that.

### CODE REVIEW

**Review by hemajv — APPROVED** [review]
/lgtm

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Pull request merged**
