### PR TITLE
fixed more html files with merge conflicts

### PR DESCRIPTION
**Pull request by oindrillac**
https://aicoe-aiops.github.io/ocp-ci-analysis/README.html still seems to be broken coz of merge conflicts. Modified the htmls to fix these

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
@oindrillac - the build check is failing here.

**Comment by oindrillac** [comment]
there is no aicoe yaml in this branch coz this is solely for the jb site, i think thats why this is failing

**Comment by aakankshaduggal** [comment]
@oindrillac - should we just merge it manually then?

**Comment by oindrillac** [comment]
ghp import overwrites our standard structure. We can add aicoe yaml to this branch as well, but I dont see a strong purpose of that since we are doing our container image builds off `master`

**Comment by oindrillac** [comment]
> @oindrillac - should we just merge it manually then?

yes, i think so. Are you able to do that?

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm

**Pull request merged**
