### PR TITLE
tracking superset dashboard json on repo

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies
Adding saved superset dashboard json to repo. This json can be used to set up dashboards on Smaug Jupyterhub once available.

related #393, #388

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by aakankshaduggal — COMMENTED** [review]
/lgtm
/approve

**Review by MichaelClifford — COMMENTED** [review]
:+1: 

What is the reason for removing the reports/figures/.gitkeep?

**Comment by oindrillac** [comment]
> What is the reason for removing the reports/figures/.gitkeep?

Removed the directory since I figured we didn't have a need for this. I can restore this if you think this could be useful later. 👍

**Comment by oindrillac** [comment]
That definitely makes sense. Restored the directory 👍

**Comment by MichaelClifford** [comment]
thanks! 
/approve

**Pull request merged**
