### PR TITLE
import resuable modules across notebooks

### LINKED ISSUE #98: Redefining of functions across notebooks in the repository
**Is your feature request related to a problem? Please describe.**

There are a few functions that are re-defined across multiple notebooks eg: `calc_flakiness_score()`, `decode_run_length` etc. Having duplicate functions over different notebooks which are a part of the same project could increase the maintainability of code.

**Describe the solution you'd like**
As a software engineer creating notebooks for the project, I want to refactor the code to reduce duplication of modules so that the code is more easily maintainable. This can be achieved by importing the required modules across notebooks.

The [ipynb](https://github.com/ipython/ipynb) package can be used for importing jupyter notebooks and modules therein like regular .py files.

### PR DESCRIPTION
**Pull request by oindrillac**
## Related Issues and Dependencies
Resolves #98 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements
In this PR, I have removed the duplicate function definitions across notebooks to improve maintainability of code.
We are now importing the following functions/modules across notebooks keeping the main function definition only in the primary notebook.

* `decode_run_length()`
* `calc_flakiness_score()`
* `calc_consecutive_failures()`
* `calc_flake_edges()`
* `flake_edge_end()`
* `calc_optimal_flakiness_score()`

We are using the .ipynb function to import modules from python notebooks similar to scripts.

### CODE REVIEW

**Comment by oindrillac** [comment]
This is the result of the initial pre-commit test which caught some issues which slipped my attention.

```
notebooks/failure-type-classification/background/testgrid_flakiness_detection.ipynb#In[40]:1:1: E402 module level import not at top of file
notebooks/data-sources/Sippy/stage/sippy-analysis.ipynb#In[2]:2:1: F401 'ipynb' imported but unused
notebooks/data-sources/Sippy/stage/sippy-analysis.ipynb#In[4]:1:1: E402 module level import not at top of file
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[2]:4:1: F401 'ipynb' imported but unused
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:1:1: E402 module level import not at top of file
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:2:1: E402 module level import not at top of file
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:2:1: F401 'ipynb.fs.defs.testgrid_flakiness_detection.calc_flakiness_score' imported but unused
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:2:1: F401 'ipynb.fs.defs.testgrid_flakiness_detection.calc_consecutive_failures' imported but unused
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:2:1: F401 'ipynb.fs.defs.testgrid_flakiness_detection.calc_flake_edges' imported but unused
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[4]:2:1: F401 'ipynb.fs.defs.testgrid_flakiness_detection.flake_edge_end' imported but unused
notebooks/data-sources/TestGrid/testgrid_indepth_EDA.ipynb#In[1]:1:1: F401 'ipynb' imported but unused
notebooks/data-sources/TestGrid/testgrid_indepth_EDA.ipynb#In[2]:1:1: E402 module level import not at top of file

```
* the function imports which were imported but unused were originally imported since they were being used in another function which was also a duplicate function. So importing that eliminated the need of importing the child functions, so i removed them
* seems like an explicit import of the `ipynb` package is not needed for the import statement, so removed that as well

However, after making the above changes, and fixing the issues, this is the current status of the pre-commit test:
```
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[32]:1:1: E402 module level import not at top of file
notebooks/failure-type-classification/stage/failure_type_classifier.ipynb#In[32]:2:1: E402 module level import not at top of file
notebooks/failure-type-classification/background/testgrid_flakiness_detection.ipynb#In[40]:1:1: E402 module level import not at top of file
notebooks/data-sources/Sippy/stage/sippy-analysis.ipynb#In[4]:1:1: E402 module level import not at top of file
```

this is catching the following import statement `from ipynb.fs.defs.testgrid_EDA import decode_run_length` which is below the line where I set the path to the notebook to be imported which is causing the test to fail.

image

Any recommendations on how to set the path before the import and yet have the import statement at the top of the notebook?

cc: @MichaelClifford

**Comment by Shreyanand** [comment]
Maybe this can help: https://stackoverflow.com/questions/36827962/pep8-import-not-at-top-of-file-with-sys-path

**Comment by oindrillac** [comment]
> Maybe this can help: https://stackoverflow.com/questions/36827962/pep8-import-not-at-top-of-file-with-sys-path
> 
> Easiest would be this answer https://stackoverflow.com/a/38338146

Thanks @Shreyanand. That seemed to ignore that particular line when i ran it locally :)

**Review by MichaelClifford — APPROVED** [review]
:+1:  Nice Notebook refactoring

**Pull request merged**
