### PR TITLE
Add notebooks and index.mdx files for publishing on the operate-first site

### PR DESCRIPTION
**Pull request by MichaelClifford**
## Related Issues and Dependencies

Related to issue #34, publishing content on Op1st website.   

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Adds two additional *.mdx files in each to the "notebooks" directory so that remote content in this repo can be rendered directly on operate-first.github.io 

## Description

Also had to make a couple minor changes to `notebooks/TestGrid_indepth_EDA.ipynb` and `notebooks/testgrid_feature_confirmation.ipynb` to make the newly added pre-commit githooks happy : )

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@tumido I updated my notebooks based on the pre-commit failure (added with  #33 ), then force pushed the changes, but sesheta appears to not be checking the updated code. For example, it reports the following error:  

`notebooks/TestGrid_indepth_EDA.ipynb#In[1]:7:1: F401 'scipy.spatial.distance' imported but unused`

However, we can see in the image here, that that error is no longer relevent. 

image

I've ran the "/retest" at least once with the same results. Is there something else that needs to happen to get sesheta to check the newly pushed code?

**Comment by oindrillac** [comment]
@MichaelClifford I see you have added the .mdx files needed for rendering the notebooks which is necessary for publishing the notebooks. However, I am not sure about creating a copy of the notebooks since that could add redundancy. Can you possibly add the `notebooks` directory as a separate source in the `content-sources.yaml` and include the .mdx files within them?

**Comment by MichaelClifford** [comment]
@oindrillac good point, and I agree this is not an ideal set up. My initial attempt did try to do exactly that, but I think since I already added the `docs/publish` repo in `content-sources.yaml` for the project-doc.md file, there was a conflict when adding a second content source from the same repo, but with a different directory.  Maybe I was doing it wrong, but it seemed like two content-sources from the same repo was not allowed. Do you have any examples of getting this situation to work I could follow? Or know of any additional setup I'd need to do to get this to work correctly?

**Comment by oindrillac** [comment]
I think @hemajv tried something similar with the continuous deployment repo. See an example [here](https://github.com/hemajv/operate-first.github.io/blob/master/content-sources.yaml). It think the rendering worked fine except the relative linking. I can also give this a try with the ocp-ci repo and let you know what I find

**Comment by MichaelClifford** [comment]
Thanks @oindrillac I'll take a look and see if I can make the appropriate changes to the operate first repo to avoid duplicate files here.

**Comment by MichaelClifford** [comment]
@oindrillac thanks for sharing @hemajv 's example. I've updated the repo here and successfully tested it locally, so it should no longer require duplicate notebooks. It may be worth adding some additional documentation to the [op1st repo](https://github.com/operate-first/operate-first.github.io) as the current instructions aren't that clear with regard to notebooks in remote content sources. Happy to help with that if needed :smile:

**Comment by MichaelClifford** [comment]
@oindrillac or @tumido want to review this PR so we can add the content to https://operate-first.github.io/ :smiley:

**Review by oindrillac — APPROVED** [review]
LGTM :ship:

**Comment by oindrillac** [comment]
@MichaelClifford thank you. please feel free to add more clarity to the documentation :smile:

**Comment by MichaelClifford** [comment]
@tumido does the `\retest` have a limit? seems like it stops working after about 3 attempts? Or do "Success" just not appear? :smile:

**Comment by tumido** [comment]
@MichaelClifford I think for some reason there was an outage or something.. It's working again on other PRs. No idea what happened there. :slightly_frowning_face:

**Pull request merged**
