### PR TITLE
Add KPI metric visualization notebook

### PR DESCRIPTION
**Pull request by hemajv**
Co-authored-by: Aakanksha Duggal <aduggal@redhat.com>
Co-authored-by: Karanraj Chauhan <kachau@redhat.com>
Co-authored-by: Hema Veeradhi <hveeradh@redhat.com>
Co-authored-by: Isabel Zimmerman <izimmerm@redhat.com>

## Related Issues and Dependencies
#217 
## This introduces a breaking change

- [ ] Yes
- [X] No

## Description
This PR includes:
A visualization notebook, to provide a way for users to explore and visualize the available KPI using `seaborn`. We also wanted to add some interactivity using `ipywidgets` for adding filters/variables to choose from, however there are some ongoing issues due to which its currently unavailable in JH/JL. We will update it once the issue is resolved.

### CODE REVIEW

**Comment by MichaelClifford** [comment]
This notebook visualizes 2 of our metrics from the same parquet file. I think it would be great if we picked a grid (or a test) at the top and walked through a visualization for all available metrics. 

For example: if I am interested in  the "release-openshift-origin-installer-e2e-aws-upgrade-4.1-stable-to-4.1-nightly" grid on the '"redhat-openshift-ocp-release-4.1-informing"' tab, what are all the metrics and KPI's I can view to help me understand its behavior?

**Comment by hemajv** [comment]
> This notebook visualizes 2 of our metrics from the same parquet file. I think it would be great if we picked a grid (or a test) at the top and walked through a visualization for all available metrics.
> 
> For example: if I am interested in the "release-openshift-origin-installer-e2e-aws-upgrade-4.1-stable-to-4.1-nightly" grid on the '"redhat-openshift-ocp-release-4.1-informing"' tab, what are all the metrics and KPI's I can view to help me understand its behavior?

We did want to compare and read other parquet files as well, but some of the KPI metrics did not seem as interesting to visualize as they had mainly boolean values. But perhaps doing the visualizations for all KPIs on a grid/test level might be better.

**Comment by hemajv** [comment]
> This notebook visualizes 2 of our metrics from the same parquet file. I think it would be great if we picked a grid (or a test) at the top and walked through a visualization for all available metrics.
> 
> For example: if I am interested in the "release-openshift-origin-installer-e2e-aws-upgrade-4.1-stable-to-4.1-nightly" grid on the '"redhat-openshift-ocp-release-4.1-informing"' tab, what are all the metrics and KPI's I can view to help me understand its behavior?

@MichaelClifford we have now updated the notebook to contain visualizations for the different KPIs available for a selected dashboard, job pair and is ready for review!

**Comment by hemajv** [comment]
@harshad16 the pre-commit check passes successfully when I run it locally, any idea why its failing here?

**Comment by harshad16** [comment]
> the pre-commit check passes successfully when I run it locally, any idea why its failing here?

Rebase this pr would fix the pre-commit issue.

**Review by oindrillac — COMMENTED** [review]
Looks good! 👍 
Had a couple minor comments. However reviewnb doesnt seem to be working :(
maybe I'll try to post them as comments

**Comment by oindrillac** [comment]
🤷‍♀️
image

**Comment by oindrillac** [comment]
image
what does the horizontal line that runs through 80 mean? why do we have 2 test duration values for each timestamp?

**Comment by oindrillac** [comment]
image
what does true and false under pass and failure mean? what do we mean by 500 False test passes?

**Comment by hemajv** [comment]
> image
> what does true and false under pass and failure mean? what do we mean by 500 False test passes?

so we have 2 metrics, `test_passing` and `test_failure` and each of them have True or False values. 
1. `test_passing` - "True" means that the test passed successfully and "False" indicates that the test pass was not successful
2. `test_failures` - "True" means that the test failed and "False" indicates that the test did not fail.

Now, it is important to note that if a test did not pass successfully i.e. `test_pass` was "False", it does not necessarily mean that it "failed", it is possible that the test could be attributed to other status values such as those mentioned in https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/cell_labels_in_testgrid.md. So 500 "False" test passes would mean that there were 500 tests that did not pass successfully, but could have had a different test status.

**Comment by oindrillac** [comment]
> > image
> > what does true and false under pass and failure mean? what do we mean by 500 False test passes?
> 
> @oindrillac so we have 2 metrics, `test_passing` and `test_failure` and each of them have True or False values.
> 
> 1. `test_passing` - "True" means that the test passed successfully and "False" indicates that the test pass was not successful
> 2. `test_failures` - "True" means that the test failed and "False" indicates that the test did not fail.
> 
> Now, it is important to note that if a test did not pass successfully i.e. `test_pass` was "False", it does not necessarily mean that it "failed", it is possible that the test could be attributed to other status values such as those mentioned in https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/cell_labels_in_testgrid.md. So 500 "False" test passes would mean that there were 500 tests that did not pass successfully, but could have had a different test status.

So, out of 100% tests, if 17% are True ie. have Test Pass labels, shouldn’t 100-17 = 83% have Test Pass as False? When test pass is true, it means that it contains the test pass label, so test pass false would include all tests which do not have a test pass label true right?

**Comment by hemajv** [comment]
> > > image
> > > what does true and false under pass and failure mean? what do we mean by 500 False test passes?
> > 
> > 
> > @oindrillac so we have 2 metrics, `test_passing` and `test_failure` and each of them have True or False values.
> > 
> > 1. `test_passing` - "True" means that the test passed successfully and "False" indicates that the test pass was not successful
> > 2. `test_failures` - "True" means that the test failed and "False" indicates that the test did not fail.
> > 
> > Now, it is important to note that if a test did not pass successfully i.e. `test_pass` was "False", it does not necessarily mean that it "failed", it is possible that the test could be attributed to other status values such as those mentioned in https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/docs/cell_labels_in_testgrid.md. So 500 "False" test passes would mean that there were 500 tests that did not pass successfully, but could have had a different test status.
> 
> So, out of 100% tests, if 17% are True for Test Passing ie. they have Test Pass labels, shouldn’t 100-17 = 83% have Test Pass as False? When Test Pass is True, it means that it contains the Test Pass label, so Test Pass False would include all tests which do not have a Test Pass label True right?

Ah yes thanks for catching that, so this was due to the fact that there were NaN values in the data frame. I have updated the visualization to drop the NaN values and added a markdown to the cell explaining the same! :+1:

**Comment by aakankshaduggal** [comment]
> image
> what does the horizontal line that runs through 80 mean? why do we have 2 test duration values for each timestamp?

Here, all the tests other than `Overall` have the value 80. We will add an explanation for this :+1:

**Comment by hemajv** [comment]
Updated the notebook with all the above mentioned comments!

**Pull request merged**
