### PR TITLE
Updated the notebook by keeping the date static

### LINKED ISSUE #436: Fail to extract the metrics for given job name in the telemetry_EDA notebook
**Describe the bug**
Fail to get installer info for the job/build_id in the [notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Telemetry/telemetry_EDA.ipynb). The issue that we are having here is we have one job_name and corresponding build_id extracted from [testgrid_metadata_EDA](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/61e1d84d43cf06f46fc144a03fa084c9bf6e63b0/notebooks/data-sources/TestGrid/testgrid_metadata_EDA.ipynb) notebook. In telemetry notebook, we have a dynamic value for the timestamp. Therefore, at any point of time we will be extracting the info for a given job_name/build_id from the 6 hours before timestamp. Hence, if any job_name/build_id is giving us an output metrics at some time, it may give null value at different time. 

**To Reproduce**
1. Go to '[notebook](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/Telemetry/telemetry_EDA.ipynb)'
2. Run 
3. Issue at cell [9]

**Expected behavior**
Expect to give output at all times.

### PR DESCRIPTION
**Pull request by suppathak**
## Related Issues and Dependencies
#436 

## This introduces a breaking change

- [ ] Yes
- [x] No

## Description
The issue was that we were not able to extract telemetry metrics for a given job_name and build_id at all time. The issue is addressed by keeping the date static. This is not an optimal solution since we are more interested in extracting the metrics value for different dates. Hence it is presently in WIP state. 

Closes #436

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@suppathak is this still a WIP PR?

**Comment by suppathak** [comment]
> @suppathak is this still a WIP PR?

Hi @MichaelClifford ,
Yes, It is still in [WIP] . Although, providing a fixed date, the notebook runs smoothly giving outputs. However, our plan is to make a date continuously changing depending upon whenever we run the notebook. Hence, working on that.

**Comment by suppathak** [comment]
The notebook has been updated for extracting metric values for fixed job name, build id and fixed date. The reason behind taking fixed date is the data in the telemetry are culled more often then test grid. If we need the metric value for some other job name/build id. We may need to check the date and see if I is available on telemetry database.

**Comment by chauhankaranraj** [comment]
Adding /hold so that PR isn't merged before some of the comments are addressed :sweat_smile:

**Comment by MichaelClifford** [comment]
oops, I think /hold may need to be on its own line
@suppathak  can you still make the requested changes in a follow up pr?

**Comment by suppathak** [comment]
> oops, I think /hold may need to be on its own line @suppathak can you still make the requested changes in a follow up pr?

Yes, I am making changes. Thanks :)

**Comment by chauhankaranraj** [comment]
> oops, I think /hold may need to be on its own line

Aah okay that explains why sesheta didn't hold it :)

**Pull request merged**
