### PR TITLE
update metric notebook template

### PR DESCRIPTION
**Pull request by hemajv**
## Related Issues and Dependencies

depends on #174 

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements
Updating the `metric_template` notebook to use the latest generated data set and reflect the updated `testgrid_labelwise_encoding` helper function introduced in the PR: #174

### CODE REVIEW

**Comment by hemajv** [comment]
/hold
until #174 is merged

**Review by oindrillac — COMMENTED** [review]
/lgtm

**Pull request merged**
