### PR TITLE
In-depth TestGrid EDA Notebook

### LINKED ISSUE #15: Understand the testgrid ecosystem
Have a look at https://github.com/GoogleCloudPlatform/testgrid and the video linked from there.
Testgrid already applies some logic to the test runs, like identifying boards with flaky tests, or boards without tests reporting in. You can also report some additional metrics like test coverage.

1. is there a central definition for the data uploaded to RH testgrid? Test status, name, infra (gws)
2. is there some tooling to download the data from testgrid, in python? 
3. is there some prior work on analyzing testgrid data at scale? blogs?

### PR DESCRIPTION
**Pull request by MichaelClifford**
This PR should close #15 and #17. 

Here we add a notebook that uses a sample of the TestGrid data to answer the following questions:  

- How comparable are the testgrids?
- How do we analyze them in aggregate to learn from their combined behavior?
- How many/ which tests do they all have in common?
- Are their time series dates comparable?
- Are there sub-groups that should only be compared with one another?
- Is looking at the grid matrices independent of test names a valid approach for issue identification?
- What is the expected behavior of a test over time across multiple jobs.
- How does the entire test platform/specific tests perform on a given day?
- How does the entire test platform behavior evolve over time.
- Is there sufficient data here for useful ML approaches?
- Can we develop some meaningful alerting/ problem identification with the results of the above questions?

Its a rather large notebook that could probably benefit from some refactoring, being broken into smaller pieces and converting some of the sections into re-usable methods for future users to ease their interaction with the Testgrid data. But I will address that in later PRs.

### CODE REVIEW

**Comment by SankBad** [comment]
Hi @MichaelClifford ,

Great work and detailed analysis. 
Just added a few comments :smile:

**Review by SankBad — APPROVED** [review]
LGTM :balloon:

**Review by aakankshaduggal — APPROVED** [review]
Looks neat and well explained :ship:

**Comment by MichaelClifford** [comment]
@durandom Do you want to review this PR further before its merged?

**Review by durandom — APPROVED** [review]
looks great to me, especially with the previous notebook. I'd love to see them rendered on the op1st website

**Comment by durandom** [comment]
@tumido @martinpovolny  why is @sesheta not working on this PR? 
Shouldnt she merge the PR and lint the notebook?

**Comment by MichaelClifford** [comment]
@durandom :+1: I've added the [project doc](https://operate-first.github.io/aici/project-doc) to the operate first website earlier this week. Once this PR is merged I'll go ahead and add both notebooks as well.

**Comment by tumido** [comment]
Replying to: https://github.com/aicoe-aiops/ocp-ci-analysis/pull/27#issuecomment-719498176

I think we need to pull new changes from the template to the ds repos to get sesheta working on it. It's missing `.aicoe.yaml`. And when we're at it, we may want to pull the rest of the changes as well, adding the pre-commit support etc.

**Comment by tumido** [comment]
@MichaelClifford @durandom Sesheta should start working with https://github.com/aicoe-aiops/ocp-ci-analysis/pull/31 (it merges all the changes from the template in here, updates OWNERS, enables `pre-commit` and adjusts the notebooks to comply with pre-commit)

**Comment by goern** [comment]
`OWNERS` should not be modified by a bot, or changes incorporated from a template project, as this opens the door for unintended side effects (code maintainer invasion?)

**Comment by tumido** [comment]
@goern let's not hijack this PR any further and discuss the rest of the template updates related stuff either in #31 or at https://github.com/thoth-station/kebechet/issues/540

**Pull request merged**
